### ISSUE TITLE
A way to add packages in the Melody.toml after lock

### ISSUE THREAD

**Issue by mapaiva** [mdy/melody#7]
Is there any way that let me add a package inside the `Melody.toml` file and `Melody.lock` after create them?

Because if I use `melody lint` melody shows me that the new package should be a dependency.

**Comment by rykov** [comment]
`Melody.toml` is meant to be a human-friendly config, so in version 0.3.0 and prior, you'll need to manually add dependencies after initialization and then run `melody install` to install and lock.

That said, I've just added `add` and `remove` commands to master (c58721324c10d723fcfecb3f84da5cd83e17e17f) to add/remove dependencies and run `install` for you. It will be available in the next release.

**Comment by mapaiva** [comment]
Awesome!! :tada:

Thanks for the replay
